name: Build for Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      # Secrets can't be checked in `if` directly. Forks without this secret skip the Sentry upload.
      SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Install MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Perform Build
      run: |
        mkdir ${{ steps.strings.outputs.build-output-dir }}
        cd ${{ steps.strings.outputs.build-output-dir }}
        cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -S ${{ github.workspace }} -DCMAKE_CXX_COMPILER=cl -DCMAKE_C_COMPILER=cl
        ninja

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: |
          ${{ steps.strings.outputs.build-output-dir }}/CastingEssentials.dll
          ${{ steps.strings.outputs.build-output-dir }}/CastingEssentials.pdb

    # This is used by Flask for automatic error reporting.
    - name: Setup Sentry CLI
      uses: mathieu-bour/setup-sentry-cli@v1
      if: github.event_name == 'push' && env.SENTRY_TOKEN != ''
      with:
        version: 2.21.2
        token: ${{ env.SENTRY_TOKEN }} # from GitHub secrets
        organization: the-james-multiverse
        project: flask

    - name: Upload Debug Symbols to Sentry
      if: github.event_name == 'push' && env.SENTRY_TOKEN != ''
      run: |
        sentry-cli debug-files check ${{ steps.strings.outputs.build-output-dir }}/CastingEssentials.pdb
        sentry-cli debug-files upload --include-sources ${{ steps.strings.outputs.build-output-dir }}/CastingEssentials.pdb
